### ISSUE TITLE
Vietnamese version has some spelling mistake.

### ISSUE THREAD

**Issue by trinhvanminh** [maunium/dontasktoask.com#131]
![image](https://github.com/maunium/dontasktoask.com/assets/46629193/897d14ab-9594-442a-a241-965b673aaa68)
 
 it must have a space between. And I want to make some keywords bold for reading easily.
 
 This is what i request to change.
 
![image](https://github.com/maunium/dontasktoask.com/assets/46629193/865c0d46-d6a9-4f21-a457-26a99999e7ca)

**Comment by KwiatekMiki** [comment]
you can just make a pull request with this fixed
