### ISSUE TITLE
Is a language for hindi needed?

### ISSUE THREAD

**Issue by anay-208** [maunium/dontasktoask.com#142]
Is a language for hindi needed? I can work on that and create a pull request.

However, I want to confirm just so my efforts aren't wasted.

Here are some points to note:
- Most of the indians already know english, especially developers

**Comment by LakhindarPal** [comment]
Hindi translation is already available.
Check on web: https://dontasktoask.com/hi

Check code: https://github.com/maunium/dontasktoask.com/blob/master/hi/index.html
