### ISSUE TITLE
kinda sounds rude

### ISSUE THREAD

**Issue by sachinchaudhary1808** [maunium/dontasktoask.com#154]
hey when some newbi enters in some channels or something and when they asks to ask and someone send this site to them,
it kinda feels rude can u make it more nice to sound to them ?

it would be very nice,

like this :

```
We love helping out, and we want you to get answers as quickly as possible! Here’s a simple tip to make sure your questions get noticed and answered faster: Ask your actual question right away!

Instead of starting with "Can I ask a question?" or "Is anyone there to help?"—just go ahead and explain your problem. The more details you give, the easier it is for someone to help you. Thank you...
```

**Comment by tulir** [comment]
The text is effectively frozen due to the large number of translations, so there won't be any significant changes to it. An alternative subdomain like suggested in #105 might be a reasonable solution.

**Comment by valerio-bozzolan** [comment]
> The text is effectively frozen due to the large number of translations, so there won't be any significant changes to it. An alternative subdomain like suggested in [#105](https://github.com/maunium/dontasktoask.com/issues/105) might be a reasonable solution.

What? Are you proposing an alternative subdomain just to don't be aggressive? lol

BTW the "alternative subdomain" was not suggested from the mentioned link.

**Comment by valerio-bozzolan** [comment]
About this assertion:

> The text is effectively frozen due to the large number of translations

Do you think is not possible to adjust 3 words, without causing any extra work for translators? I assumed it was an easy change.

For example, I would encourage such minimal change 😸

```
-This is bad form, for several reasons.
+This is not ideal, for several reasons.
```

If such proposal is somehow welcomed, I can share other similar minimal changes in a merge request.
