### ISSUE TITLE
Hebrew translation has some typos 

### ISSUE THREAD

**Issue by RedCommand-dev** [maunium/dontasktoask.com#47]
The Hebrew translation has some typos.

**Comment by jonatan1609** [comment]
> The Hebrew translation has some typos.

Hi, i would like to know about them, I know I missed a “ י “ and I’ll make a pr to fix it as soon as possible. Thanks

**Comment by mtatko** [comment]
Hi there!
@jonatan1609, are you still willing to create a PR fixing those typos?
Thanks!

**Comment by RedCommand-dev** [comment]
I'm working on it.

**Comment by jonatan1609** [comment]
> Hi there!
> 
> @jonatan1609, are you still willing to create a PR fixing those typos?
> 
> Thanks!

Not anymore. The current version has no typos iirc

**Comment by jonatan1609** [comment]
@tulir that issue can be closed.
