### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by Kloetzchengrafikk** [maunium/dontasktoask.com#51]
Please change
Gibt es hier irgendeinen Java-Experten, der mir bei meinem Problem, was auch immer es ist, selbst wenn es nichts mit Java zu tun, helfen könnte - oder könnte mir wenigstens irgendjemand antworten? 

to

Gibt es hier irgendeinen Java-Experten, der mir bei meinem Problem, was auch immer es ist, selbst wenn es nichts mit Java zu tun hat, helfen könnte - oder könnte mir wenigstens irgendjemand antworten? 

And please change
Die Lösung ist nicht zum Fragen zu fragen, sondern einfach zu fragen. Es ist unwahrscheinlich, dass jemand der nur ab in den Kanal guckt deine "Frage zum Fragen" für interessant hält und tatsächlich auf deine Fragen antworten wird. 

to

Die Lösung ist nicht zum Fragen zu fragen, sondern einfach zu fragen. Es ist unwahrscheinlich, dass jemand der nur ab und zu in den Kanal guckt deine "Frage zum Fragen" für interessant hält und tatsächlich auf deine Fragen antworten wird. 

(I'm german)

Thanks

**Comment by MangoIV** [comment]
#55 could resolve this issue.

**Comment by MangoIV** [comment]
I'd be happy if @Kloetzchengrafikk would take a look at my fixes, thanks in advance.
