### ISSUE TITLE
Consider adding CODEOWNERS

### ISSUE THREAD

**Issue by revi** [maunium/dontasktoask.com#71]
I'd like to review changes to Korean translations (ie. #69 ) but I don't want to get notified for every PR which is probably not something I can even read.

So... Can we add [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) as an opt-in basis so I (or those who also want to review changes made to the repo) can get review notification when someone opens a PR against languages directory? (Well it might send review for non-translation PRs but I think those who opt in to this can live with that).

**Comment by revi** [comment]
Ouch,

> The people you choose as code owners must have write permissions for the repository.

Nevermind in this case. >_> I guess I'll figure out some way to monitor the repo without receiving all the repo emails.

**Comment by tulir** [comment]
Giving write access to the repo might be fine, I think I can just protect the master branch to prevent pushing directly

**Comment by revi** [comment]
Well in that case -- if you feel like it reopen it, and I can probably write a quick PR to add the file tomorrow.
